"""
Django settings for neuroezotericabackend project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from decouple import config
from urllib.parse import urlparse
from datetime import timedelta


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY", None, cast=str)

DEBUG = config("DEBUG", default=True, cast=bool)

USE_SECURE_HTTPS = config("USE_SECURE_HTTPS", default=False, cast=bool)
if not USE_SECURE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

INTERNET_URL = config("INTERNET_URL", default='http://127.0.0.1:8000')
PRODUCTION_DATABASE = config("PRODUCTION_DATABASE", cast=bool, default=False)
INTERNET_DOMAIN = urlparse(INTERNET_URL).netloc

APPEND_SLASH=False

ADMIN_PASSWORD = config("ADMIN_PASSWORD", cast=str, default="qwerty123")
ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ORIGIN = ["*"]
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
CORS_ALLOW_HEADERS = [
    "Accept", "Origin",
    "Content-Type",
    "X-Requested-With",
    "Authorization",
]

ASGI_APPLICATION = 'settings.asgi.application'
WSGI_APPLICATION = 'settings.wsgi.application'

INSTALLED_APPS = [
    'mobile_api.apps.Config',
    'admin.apps.Config',
    'channels',
    'daphne',
    
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [    
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.CrossOriginHeaderMiddleware',
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'admin.middleware.context_processors.permission_helper',
            ],
        },
    },
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

if PRODUCTION_DATABASE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': '92vXu9S03b2RgstD9ZeGO9l6LJbMJGqeOWYBlpzeQvwh2QHbFB',
            'HOST': 'postgres',
            'PORT': '5432',
            'OPTIONS': {'sslmode': 'disable'},
        },
        'mg': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': '92vXu9S03b2RgstD9ZeGO9l6LJbMJGqeOWYBlpzeQvwh2QHbFB',
            'HOST': 'localhost',
            'PORT': '5432',
            'OPTIONS': {'sslmode': 'disable'},
        }
    }
    # CHANNEL_LAYERS = {
    #     "default": {
    #         "BACKEND": "channels_redis.core.RedisChannelLayer",
    #         "CONFIG": {
    #             "hosts": [("redis", 6379)],
    #         },
    #     },
    # }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': "channels.layers.InMemoryChannelLayer"
    }
}

# Internationalization
LANGUAGE_CODE = 'ru-ru'

USE_I18N = True
USE_TZ = False
TIME_ZONE = 'Europe/Moscow'

TIME_FORMAT = "%H:%M:%S.%f%z"
DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%f%z"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_ENGINE = None
AUTH_USER_MODEL = ""

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,
    'SEARCH_PARAM': 'query',
    'PAGE_SIZE': 20,
}
SESSION_COOKIE_AGE = timedelta(days=30).total_seconds()

if USE_SECURE_HTTPS:
    SESSION_COOKIE_SAMESITE = ""
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True

# Static files

STATIC_URL = "/static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [
    BASE_DIR / "static"
]


# Third Party Credencials

PRODAMUS_URL = config("PRODAMUS_URL", cast=str, default="https://demo.payform.ru/")
